
spring:
  application:
    name: config-client

  cloud:
    config:
      profile: dev
      discovery:
        enabled: true
        service-id: config-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
